run:
  deadline: 3m

linters:
  enable:
    - deadcode
    - gas
    - gocritic
    - golint
    - gosimple
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - exportloopref
    - depguard
    - dupl
    - gocyclo
    - prealloc
  disable:
    - lll
    - gosec
    - interfacer
    - maligned
  fast: false

linters-settings:
  gocritic:
    enabled-checks:
      - appendAssign
      - argOrder
      - assignOp
      - badCall
      - badCond
      - badRegexp
      - boolExprSimplify
      - captLocal
      - caseOrder
      - codegenComment
      - commentFormatting
      - commentedOutCode
      - commentedOutImport
      - defaultCaseOrder
      - deferUnlambda
      - deprecatedComment
      - dupArg
      - dupBranchBody
      - dupCase
      - dupImport
      - dupSubExpr
      - elseif
      - emptyFallthrough
      - emptyStringTest
      - equalFold
      - evalOrder
      - exitAfterDefer
      - filepathJoin
      - flagDeref
      - flagName
      - ifElseChain
      - indexAlloc
      - initClause
      - mapKey
      - methodExprCall
      - nestingReduce
      - newDeref
      - nilValReturn
      - offBy1
      - rangeExprCopy
      - regexpMust
      - regexpPattern
      - regexpSimplify
      - ruleguard
      - singleCaseSwitch
      - sloppyLen
      - sloppyReassign
      - sloppyTypeAssert
      - sortSlice
      - stringXbytes
      - switchTrue
      - truncateCmp
      - typeAssertChain
      - typeSwitchVar
      - typeUnparen
      - underef
      - unlabelStmt
      - unlambda
      - unnamedResult
      - unnecessaryBlock
      - unslice
      - valSwap
      - weakCond
      - whyNoLint
      - wrapperFunc
      - yodaStyleExpr
    settings:
      ruleguard:
        rules: "rules.go"
